<div class="program">
      <form method="post" action="<?= App::config('url') ?>login/autorizacija">
            <div class="container">
                  <div>

                        <div>
                              <h1 class="h3 font-weight-normal text-center">Ulogirajte se, molimo</h1>
                        </div>
                        <div class="container align-items-center">


                                    <div>
                                          <label class="col-form-label" for="inputEmail" class="sr-only">Email</label>
                                          <input type="email" value="<?= $email ?>" id="email" name="email" class="form-control" placeholder="Email adresa" required autofocus>
                                    </div>


                                    <div>
                                          <label class="col-form-label" for="inputPassword" class="sr-only">Password</label>
                                          <input type="password" id="password" name="password" class="form-control" value="o" required>
                                    </div>

                        </div>

                        <div>
                              <label>
                                    <input type="checkbox" value="remember-me"> Zapamti me
                              </label>
                        </div>
                        <div class="d-flex align-items-center">
                              <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                        </div>
                  </div>
                  <p class="mt-5 mb-3 text-muted"><?= $poruka ?></p>
      </form>
</div>

<!-- <form  method="post" action="<?= App::config('url') ?>login/autorizacija">
<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <h3 class="mb-5">Sign in</h3>
  
              <div class="form-outline mb-4">
                <input type="email" value="<?= $email ?>" id="email" class="form-control form-control-lg" />
                <label class="form-label">Email</label>
              </div>
  
              <div class="form-outline mb-4">
                <input type="password" value="a" id="password" class="form-control form-control-lg" />
                <label class="form-label">Password</label>
              </div>
  
              <!-- Checkbox -->
              <!--<div class="form-check d-flex justify-content-start mb-4">
                <input
                  class="form-check-input"
                  type="checkbox"
                  value=""
                />
                <label class="form-check-label"> Remember password </label>
              </div>
  
              <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
  
              <hr class="my-4">
  
              <button class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;" type="submit"><i class="fab fa-google me-2"></i> Sign in with google</button>
              <button class="btn btn-lg btn-block btn-primary mb-2" style="background-color: #3b5998;" type="submit"><i class="fab fa-facebook-f me-2"></i>Sign in with facebook</button>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  </form> -->