<div class="program">
      <form method="post" action="<?= App::config('url') ?>loginuser/autorizacija">
            <div class="container">
                  <div>

                        <div>
                              <h1 class="h3 font-weight-normal text-center">Ulogirajte se, molimo</h1>
                        </div>
                        <div class="container align-items-center">


                                    <div>
                                          <label class="col-form-label" for="inputEmail" class="sr-only">Email</label>
                                          <input type="email" value="<?= $email ?>" id="email" name="email" class="form-control" placeholder="Email adresa" required autofocus>
                                    </div>


                                    <div>
                                          <label class="col-form-label" for="inputPassword" class="sr-only">Password</label>
                                          <input type="password" id="password" name="password" class="form-control" value="tele" required>
                                    </div>

                        </div>

                        <div>
                              <label>
                                    <input type="checkbox" value="remember-me"> Zapamti me
                              </label>
                        </div>
                        <div class="d-flex align-items-center">
                              <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                        </div>
                  </div>
                  <p class="mt-5 mb-3 text-muted"><?= $poruka ?></p>
      </form>
</div>