<form method="post" 
action="<?=App::config('url')?>registracija/promjena/<?=$e->id?>">
  <h4 class="text-center">Unesite podatke</h4>
  
  <label>Prezime
    <input type="text" name="prezime" value="<?=$e->prezime?>" />
  </label>
<br />
  <label>Ime
    <input type="text" name="ime" value="<?=$e->ime?>" />
  </label>

  <br />
  <label>Username
    <input type="text" name="username" value="<?=$e->username?>" />
  </label>
  <br />
  <label>Password
    <input type="text" name="password" value="<?=$e->password?>" />
  </label>
  <br />
  <label>Email
    <input type="email" name="email" value="<?=$e->email?>" />
  </label>
  <br />
  <label>Country
    <input type="text" name="country" value="<?=$e->country?>" />
  </label>
  <br />
  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>index">Odustani</a>
    </div>
    <div class="large-6 cell">
       <a href="<?=App::config('url')?>index"> <input type="submit" class="button expanded" value="Registriraj me"></input>
       </a>
      </div>
  </div>


</form>