<div class="container d-flex program">

        



<section class="pt-4">
  <div class="container px-lg-5">
    <!-- Page Features-->
    <div class="row gx-lg-5">
      <div class="col-lg-6 col-xxl-4 mb-5">
        <div class="card bg-light border-0 h-100">
          <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
            <div class="feature bg-secondary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-people-fill"></i></div>
            <h2 class="fs-4 fw-bold">Korisnici</h2>
            <p class="mb-0">Uredite, dodajte ili obrišite korisnike prema izboru</p>
            <a href="<?= App::config('url') ?>korisnici" class="btn btn-secondary">Uredi</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-xxl-4 mb-5">
        <div class="card bg-light border-0 h-100">
          <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
            <div class="feature bg-secondary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-images"></i></div>
            <h2 class="fs-4 fw-bold">Galerija</h2>
            <p class="mb-0">Uređivanje galerije slika</p>
            <a href="<?= App::config('url') ?>galerija/admin" class="btn btn-secondary">Uredi</a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-xxl-4 mb-5">
        <div class="card bg-light border-0 h-100">
          <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
            <div class="feature bg-secondary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-images"></i></div>
            <h2 class="fs-4 fw-bold">Upload slike</h2>
            <p class="mb-0">Dodajte sliku</p>
            <a href="<?= App::config('url') ?>galerija/novaSlika/<?=$id?>" class="btn btn-secondary">Dodaj</a>
          </div>
        </div>
      </div>
</div>
</div>

</div>