<div class="card row" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="">
  <div class="card-body">
    <h5 class="card-title">Uredi korisnike</h5>
    <p class="card-text text-align: center;">Lorem Ipsum1</p>
    <a href="<?=App::config('url')?>korisnici" class="btn btn-primary">Uredi</a>
  </div>
</div>

<div class="card row" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="">
  <div class="card-body">
    <h5 class="card-title">Uredi sadržaj</h5>
    <p class="card-text">Lorem Ipsum2</p>
    <a href="#" class="btn btn-primary">Uredi</a>
  </div>
</div>

<div class="card row" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="">
  <div class="card-body">
    <h5 class="card-title">Uredi još nešto</h5>
    <p class="card-text">Lorem Ipsum3</p>
    <a href="#" class="btn btn-primary">Uredi</a>
  </div>
</div>