
    <div class="container program">
    <table><tr>
        <?php foreach ($entiteti as $e)  : ?>
           
       <?php echo
       
        '<a href=' . App::config('url') . 'galerija/promjena/' . $e->id . '>' .
        '<img src=" ' . $e->slika . '" class="img-thumbnail" width="300px;" height="200px;"></a>' 
         ; 
         
         
         ?>

       
        <?php endforeach; ?>

        </tr></table>

    </div>
