Detalji slika

<table>
    <thead>
        <tr>
            <th>Slika</th>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Kategorija</th>
            <th>Boja</th>
            <th>Pletivo</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><img src="<?=$e->slika?>" class="img-thumbnail" style="width: 70px;height: 60px;"></td>
                <td><?=$e->naziv?></td>
                <td><?=$e->opis?></td>
                <td><?=$e->kategorija?></td>
                <td><?=$e->boja?></td>
                <td><?=$e->pletivo?></td>
                <td>
                <a href="<?=App::config('url')?>/galerija/promjena/ <?php $e->id ?>">         
                <i style="color: blue;" class="bi bi-pencil"></i>
                     </a>
                 
                        <a href="<?=App::config('url')?>galerija/brisanje/<?=$e->sifra?>">
                            <i style="color: red;" 
                            class="step fi-page-delete size-36"></i>
                        </a>
                        
                           
                   
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>