<form method="post" 
enctype="multipart/form-data"
action="<?=App::config('url')?>korisnici/promjena/<?=$e->id?>">
  <h4 class="text-center">Detalji korisnika</h4>
  
  
  <label>Prezime
    <input type="text" name="prezime" value="<?=$e->prezime?>" />
  </label>
<br />
  <label>Ime
    <input type="text" name="ime" value="<?=$e->ime?>" />
  </label>

  <br />
  <label>Username
    <input type="text" name="username" value="<?=$e->username?>" />
  </label>
  <br />
  <label>Password
    <input type="text" name="password" value="<?=$e->password?>" />
  </label>
  <br />
  <label>Email
    <input type="email" name="email" value="<?=$e->email?>" />
  </label>
  <br />
  <label>Country
    <input type="text" name="country" value="<?=$e->country?>" />
  </label>
  <br />
  <label>Slika
    <input type="file" name="slika">
  </label>
  <br />
  <img src="<?=$e->slika?>" alt="">
  <br />
  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>korisnici">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>