<div class="container d-flex program">

        
OVO JE PROFIL

<!-- početak slikarenja -->

<div class="reveal" id="slikaModal" data-reveal>
    <div style="max-height: 300px; overflow: auto;">
        <img id="image" src="" alt="" />
    </div>
  
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

</div>